---
- name: Pull Grafana Docker image
  community.docker.docker_image:
    name: "grafana/grafana:latest"
    source: pull

- name: Run Grafana container
  community.docker.docker_container:
    name: "grafana"
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    restart_policy: always
